name: Cloudsmith Push Docker Image
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    name: Docker Push
    steps:
    - uses: actions/checkout@v1
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'docker'
        owner: 'jake-org'             # Your Cloudsmith account name or org name (namespace) 
        repo: 'docker-test'         # Your Cloudsmith Repository name (slug)
        republish: 'true'          # needed ONLY if version is not changing
        file: 'hellosh_image'  # docker image filename
