name: Cloudsmith Push Python 4
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    name: Python Push 4
    steps:
      - uses: actions/checkout@v1
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: 'jake-org'               # Your Cloudsmith account name or org name (namespace) 
          repo: 'python-test'           # Your Cloudsmith Repository name (slug)
          republish: 'true'            # needed ONLY if version is not changing
          file: "UNKNOWN-0.0.1-py3-none-any.whl" # Python package filename
