name: Cloudsmith Push Raw File
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    name: Raw Push
    steps:
    - uses: actions/checkout@v1
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'raw'
        owner: 'jake-org'              # Your Cloudsmith account name or org name (namespace) 
        repo: 'raw-test'          # Your Cloudsmith Repository name (slug)
        file: 'raw1.txt'        # Name of file 
        name: 'raw1'                # Name for Raw package
        summary: 'raw1'          # Optional Summary for Raw Package
        description: 'raw1'  # Optional description for Raw package
        version: ${{ github.sha }}
